export type Restaurant = {
  rank: number;
  name: string;
  region: string;
  visits: number;
  totalAmount: number;
  avgAmount: number;
  deptCount: number;
  topAgency?: string;
  lat?: number;
  lng?: number;
  placeId?: string;
  rating?: number;
  ratingCount?: number;
  phone?: string;
  hours?: string[];
  photos?: string[];
  googleMapsUri?: string;
  formattedAddress?: string;
  address?: string;
  guDong?: string;
  naverPlaceId?: string;
  naverRating?: number;
  naverVisitorReviewCount?: number;
  naverBlogReviewCount?: number;
};
